### ISSUE TITLE
Additional crypto tests needed?

### ISSUE THREAD

**Issue by ramriot** [D1plo1d/graphql-things#1]
File: src/p2pCrypto/encryption.test.js
While I work towards putting a test harness together myself I believe the following additions to the tests will prove useful in testing their security under malicious use.

Currently there are just two tests i.e.
"encrypts and decrypts back to the original value"
"does not decrypt for an incorrect key"

In addition I think there needs to be (keeping all other parameters valid):
"does not decrypt for an altered Initiation Vector"
"does not decrypt for an altered authTag"
"does not decrypt for an altered correct length ciphertext"
"throws caught error for a null cipherText"
"throws caught error for a truncated ciphertext"
"throws caught error for a valid ciphertext altered by extension"

**Comment by D1plo1d** [comment]
Hey @ramriot I figured out what you meant about no updates on this repo! I thought you were talking about this *and* https://GitHub.com/tegapp/teg - which is the 3D printer side that consumes this lib.

Thanks again for the feedback here.

Anywho just thought I'd give a quick crypto update. The immediate plans are to (unfortunately) scrap the crypto in this repo. The short version of the story is that as long as users store their private keys on a central server this crypto doesn't increase a user's security as a hijacked server could just override the private keys.

So for now I'm reworking this to connect to webrtc with minimum handshake RTTs (1 RTT to be exact).

The exciting news is that this has been a valuable experiment. I have a better understanding of the challenges that would be needed to be overcome to build a good user experience here.

As always, looking forward to our next chat. Hope your staying safe during the covid times!
